### ISSUE TITLE
Plugin fails to launch on newer version of PowerToys

### ISSUE THREAD

**Issue by 0ri3nt** [Quriz/PowerToysRunScoop#11]
This recent update doesn't load the plugin properly
![image](https://github.com/user-attachments/assets/fe010535-976b-46ec-8d2e-b1eb5995ea45)

**Comment by GOD-OF-THE-GODS** [comment]
Same problem for me

![Screenshot 2024-12-17 194707](https://github.com/user-attachments/assets/cbabce94-71ed-4494-9c56-7de614225ec1)

**Comment by Quriz** [comment]
With the latest PowerToys update, they have removed the use of the Wpf.Ui library that I was using for the UI. They switched to regular WPF, which I will also have to do. 
For now, if you want to use this plugin, use PowerToys 0.86.0 or older.

**Comment by Quriz** [comment]
So now I have rebuilt the main UI and everything works again with the latest version of PowerToys! 🎉 
[Get the release here](https://github.com/Quriz/PowerToysRunScoop/releases/tag/v1.3.4).
