### ISSUE TITLE
Failed to initialize plugin

### ISSUE THREAD

**Issue by kenis1108** [Quriz/PowerToysRunScoop#9]
![image](https://github.com/Quriz/PowerToysRunScoop/assets/45393183/7719b9f0-a4e6-404e-b640-b188bdbf1869)
My PowerToys is installed with `scoop install PowerToys-Protable`
PowerToys Version：0.80.1

**Comment by Quriz** [comment]
This can happen if you didn't have an internet connection at startup. Have you tried restarting PowerToys?
